[package]
name = "slowtec-core"
version = "0.0.1"
authors = [ "slowtec GmbH" ]
license = "MIT/Apache-2.0"
publish = false

[dependencies]
chrono = "*"
failure = "*"
futures = "0.1"
log = "*"
tokio = "0.1"
