[package]
name = "slowtec-core"
version = "0.0.1"
authors = [ "slowtec GmbH" ]
license = "MIT/Apache-2.0"
edition = "2018"
publish = false

[dependencies]
chrono = "*"
failure = "*"
futures = "0.1"
log = "*"
serde = { version = "*", features = ["derive"] }
tokio = "0.1"
